/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz_Grafica;

import Clases.User;
import Controladores.Conn;
import Controladores.UserManagement;


/**
 *
 * @author nan_c
 */
public class profilePanel extends javax.swing.JPanel {
    String usuario;
    /**
     * Creates new form profilePanel
     */
    public profilePanel() {
        initComponents();   
    }
    public String getUsuario(){
        return usuario;
    }
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    public User getUserData(){
        Conn c = new Conn();
        UserManagement um = new UserManagement();
        User u= um.Search(c.Connect(),getUsuario());
        return u;
    }
    
    public void ShowUserData(){
        Conn c  = new Conn();
        UserManagement um = new UserManagement();
        User u= um.Search(c.Connect(), getUsuario());
        showUserData(u);
    }
    public void showUserData(User u){
        idUser.setText("ID: "+String.valueOf(u.getID()));
        userNameTxt.setText(u.getName());
        ageTxt.setText(String.valueOf(u.getAge()));
        genderTxt.setText(u.getGender());
        emailTxt.setText(u.getEmail());
        weightTxt.setText(String.valueOf(u.getWeight()));
        heightTxt.setText(String.valueOf(u.getHeight()));
        imcTxt.setText(String.valueOf(u.getBmi()));
        
        userNameTxt.setEditable(false);
        ageTxt.setEditable(false);
        genderTxt.setEditable(false);
        emailTxt.setEditable(false);
        weightTxt.setEditable(false);
        heightTxt.setEditable(false);
        imcTxt.setEditable(false);
  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataModifier = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        imcTxt = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        heightTxt = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        weightTxt = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        genderTxt = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        emailTxt = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        userNameTxt = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        ageTxt = new javax.swing.JTextPane();
        idUser = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de Usuario");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Genero");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peso");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Altura");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IMC");

        dataModifier.setBackground(new java.awt.Color(60, 63, 65));
        dataModifier.setForeground(new java.awt.Color(255, 255, 255));
        dataModifier.setText("Modificar Datos");
        dataModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataModifierActionPerformed(evt);
            }
        });

        imcTxt.setBackground(new java.awt.Color(60, 63, 65));
        imcTxt.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane1.setViewportView(imcTxt);

        heightTxt.setBackground(new java.awt.Color(60, 63, 65));
        heightTxt.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane2.setViewportView(heightTxt);

        weightTxt.setBackground(new java.awt.Color(60, 63, 65));
        weightTxt.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane3.setViewportView(weightTxt);

        jScrollPane4.setBackground(new java.awt.Color(60, 63, 65));

        genderTxt.setBackground(new java.awt.Color(60, 63, 65));
        genderTxt.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane4.setViewportView(genderTxt);

        emailTxt.setBackground(new java.awt.Color(60, 63, 65));
        emailTxt.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane5.setViewportView(emailTxt);

        userNameTxt.setBackground(new java.awt.Color(60, 63, 65));
        userNameTxt.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane6.setViewportView(userNameTxt);

        ageTxt.setBackground(new java.awt.Color(60, 63, 65));
        ageTxt.setForeground(new java.awt.Color(60, 63, 65));
        ageTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane7.setViewportView(ageTxt);

        idUser.setForeground(new java.awt.Color(255, 255, 255));
        idUser.setText("jLabel1");

        delete.setBackground(new java.awt.Color(60, 63, 65));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Eliminar Cuenta");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(idUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataModifier)
                        .addGap(55, 55, 55)
                        .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(idUser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataModifier)
                    .addComponent(delete))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataModifierActionPerformed
        // TODO add your handling code here:
        modificarUsuario mu = new modificarUsuario();
        mu.setUser(getUsuario());
        mu.ShowUserData();
        mu.setVisible(true);
        
    }//GEN-LAST:event_dataModifierActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        deleteU();
    }//GEN-LAST:event_deleteActionPerformed
    public void deleteU(){
        deleteUser d = new deleteUser();
        d.setVisible(true);
        d.setUser(getUsuario());
    }
    public void Menu(){
        MainMenu m = new MainMenu();
        m.setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ageTxt;
    private javax.swing.JToggleButton dataModifier;
    private javax.swing.JButton delete;
    private javax.swing.JTextPane emailTxt;
    private javax.swing.JTextPane genderTxt;
    private javax.swing.JTextPane heightTxt;
    private javax.swing.JLabel idUser;
    private javax.swing.JTextPane imcTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane userNameTxt;
    private javax.swing.JTextPane weightTxt;
    // End of variables declaration//GEN-END:variables
}
